package dos

import (
	"bootpkg/common/expands/automaticType"
)

type FcProfitReportDay struct {
	BaseDos
	ReportDate                          automaticType.Time `gorm:"column:report_date" json:"report_date" form:"report_date" uri:"report_date" `
	Online                              int                `gorm:"column:online" json:"online" form:"online" uri:"online" `                                                                                                                                         // 日活
	Profit                              float64            `gorm:"column:profit" json:"profit" form:"profit" uri:"profit" `                                                                                                                                         // 利润
	Register                            int                `gorm:"column:register" json:"register" form:"register" uri:"register" `                                                                                                                                 // 注册人数
	TotalRechargeAmount                 float64            `gorm:"column:total_recharge_amount" json:"total_recharge_amount" form:"total_recharge_amount" uri:"total_recharge_amount" `                                                                             // 总充值额
	TotalWithdrawAmount                 float64            `gorm:"column:total_withdraw_amount" json:"total_withdraw_amount" form:"total_withdraw_amount" uri:"total_withdraw_amount" `                                                                             // 总提款额
	NewMemberRechargeProbability        float64            `gorm:"column:new_member_recharge_probability" json:"new_member_recharge_probability" form:"new_member_recharge_probability" uri:"new_member_recharge_probability" `                                     // 新客充值率
	NewMemberRechargeNum                int                `gorm:"column:new_member_recharge_num" json:"new_member_recharge_num" form:"new_member_recharge_num" uri:"new_member_recharge_num" `                                                                     // 新客充值人数
	NewMemberRechargeAvAmount           float64            `gorm:"column:new_member_recharge_av_amount" json:"new_member_recharge_av_amount" form:"new_member_recharge_av_amount" uri:"new_member_recharge_av_amount" `                                             // 新客均充
	NewMemberRechargeAmount             float64            `gorm:"column:new_member_recharge_amount" json:"new_member_recharge_amount" form:"new_member_recharge_amount" uri:"new_member_recharge_amount" `                                                         // 新客充值金额
	RelativelyNewMemberRechargeNum      int                `gorm:"column:relatively_new_member_recharge_num" json:"relatively_new_member_recharge_num" form:"relatively_new_member_recharge_num" uri:"relatively_new_member_recharge_num" `                         // 次新客充值人数
	RelativelyNewMemberRechargeAvAmount float64            `gorm:"column:relatively_new_member_recharge_av_amount" json:"relatively_new_member_recharge_av_amount" form:"relatively_new_member_recharge_av_amount" uri:"relatively_new_member_recharge_av_amount" ` // 次新客均充
	RelativelyNewMemberRechargeAmount   float64            `gorm:"column:relatively_new_member_recharge_amount" json:"relatively_new_member_recharge_amount" form:"relatively_new_member_recharge_amount" uri:"relatively_new_member_recharge_amount" `             // 次新客充值金额
	OldMemberRechargeNum                int                `gorm:"column:old_member_recharge_num" json:"old_member_recharge_num" form:"old_member_recharge_num" uri:"old_member_recharge_num" `                                                                     // 老客充值人数
	OldMemberRechargeAvAmount           float64            `gorm:"column:old_member_recharge_av_amount" json:"old_member_recharge_av_amount" form:"old_member_recharge_av_amount" uri:"old_member_recharge_av_amount" `                                             // 老客均充
	OldMemberRechargeAmount             float64            `gorm:"column:old_member_recharge_amount" json:"old_member_recharge_amount" form:"old_member_recharge_amount" uri:"old_member_recharge_amount" `                                                         // 老客充值金额
	NewMemberWithdrawNum                int                `gorm:"column:new_member_withdraw_num" json:"new_member_withdraw_num" form:"new_member_withdraw_num" uri:"new_member_withdraw_num" `                                                                     // 新客充值人数
	NewMemberWithdrawAvAmount           float64            `gorm:"column:new_member_withdraw_av_amount" json:"new_member_withdraw_av_amount" form:"new_member_withdraw_av_amount" uri:"new_member_withdraw_av_amount" `                                             // 新客均充
	NewMemberWithdrawAmount             float64            `gorm:"column:new_member_withdraw_amount" json:"new_member_withdraw_amount" form:"new_member_withdraw_amount" uri:"new_member_withdraw_amount" `                                                         // 新客充值金额
	NewMemberWithdrawCount              int                `gorm:"column:new_member_withdraw_count" json:"new_member_withdraw_count" form:"new_member_withdraw_count" uri:"new_member_withdraw_count" `                                                             // 新客提款笔数
	RelativelyNewMemberWithdrawNum      int                `gorm:"column:relatively_new_member_withdraw_num" json:"relatively_new_member_withdraw_num" form:"relatively_new_member_withdraw_num" uri:"relatively_new_member_withdraw_num" `                         // 新客充值人数
	RelativelyNewMemberWithdrawAvAmount float64            `gorm:"column:relatively_new_member_withdraw_av_amount" json:"relatively_new_member_withdraw_av_amount" form:"relatively_new_member_withdraw_av_amount" uri:"relatively_new_member_withdraw_av_amount" ` // 新客均充
	RelativelyNewMemberWithdrawAmount   float64            `gorm:"column:relatively_new_member_withdraw_amount" json:"relatively_new_member_withdraw_amount" form:"relatively_new_member_withdraw_amount" uri:"relatively_new_member_withdraw_amount" `             // 新客充值金额
	RelativelyNewMemberWithdrawCount    int                `gorm:"column:relatively_new_member_withdraw_count" json:"relatively_new_member_withdraw_count" form:"relatively_new_member_withdraw_count" uri:"relatively_new_member_withdraw_count" `                 // 新客提款笔数
	OldMemberWithdrawNum                int                `gorm:"column:old_member_withdraw_num" json:"old_member_withdraw_num" form:"old_member_withdraw_num" uri:"old_member_withdraw_num" `                                                                     // 新客充值人数
	OldMemberWithdrawAvAmount           float64            `gorm:"column:old_member_withdraw_av_amount" json:"old_member_withdraw_av_amount" form:"old_member_withdraw_av_amount" uri:"old_member_withdraw_av_amount" `                                             // 新客均充
	OldMemberWithdrawAmount             float64            `gorm:"column:old_member_withdraw_amount" json:"old_member_withdraw_amount" form:"old_member_withdraw_amount" uri:"old_member_withdraw_amount" `                                                         // 新客充值金额
	OldMemberWithdrawCount              int                `gorm:"column:old_member_withdraw_count" json:"old_member_withdraw_count" form:"old_member_withdraw_count" uri:"old_member_withdraw_count" `                                                             // 新客提款笔数
	AgentInviteAwardAmount              float64            `gorm:"column:agent_invite_award_amount" json:"agent_invite_award_amount" form:"agent_invite_award_amount" uri:"agent_invite_award_amount" `                                                             // 代理邀请奖励
	AgentCommission                     float64            `gorm:"column:agent_commission" json:"agent_commission" form:"agent_commission" uri:"agent_commission" `                                                                                                 // 代理佣金
	UserInviteAwardAmount               float64            `gorm:"column:user_invite_award_amount" json:"user_invite_award_amount" form:"user_invite_award_amount" uri:"user_invite_award_amount" `                                                                 // 用户邀请奖励
	TotalBonus                          float64            `gorm:"column:total_bonus" json:"total_bonus" form:"total_bonus" uri:"total_bonus" `                                                                                                                     // 总用户奖励
	TotalBetAmount                      float64            `gorm:"column:total_bet_amount" json:"total_bet_amount" form:"total_bet_amount" uri:"total_bet_amount" `                                                                                                 // 总流水
	TotalBetCount                       int                `gorm:"column:total_bet_count" json:"total_bet_count" form:"total_bet_count" uri:"total_bet_count" `                                                                                                     // 总投注笔数
	TotalBetNetAmount                   float64            `gorm:"column:total_bet_net_amount" json:"total_bet_net_amount" form:"total_bet_net_amount" uri:"total_bet_net_amount" `                                                                                 // 总是输赢
	VenueCost                           float64            `gorm:"column:venue_cost" json:"venue_cost" form:"venue_cost" uri:"venue_cost" `                                                                                                                         // 场馆成本
	DepositCost                         float64            `gorm:"column:deposit_cost" json:"deposit_cost" form:"deposit_cost" uri:"deposit_cost" `                                                                                                                 // 代收成本
	WithdrawCost                        float64            `gorm:"column:withdraw_cost" json:"withdraw_cost" form:"withdraw_cost" uri:"withdraw_cost" `                                                                                                             // 代付成本
	MerchantCode                        string             `gorm:"column:merchant_code" json:"merchant_code" form:"merchant_code" uri:"merchant_code" `                                                                                                             // 商户code
	CreateTime                          automaticType.Time `gorm:"column:create_time;default:null" json:"create_time" form:"create_time" uri:"create_time" `                                                                                                        // 创建时间
	CreateBy                            string             `gorm:"column:create_by" json:"create_by" form:"create_by" uri:"create_by" `                                                                                                                             // 创建人
	UpdateTime                          automaticType.Time `gorm:"column:update_time;default:null" json:"update_time" form:"update_time" uri:"update_time" `                                                                                                        // 修改时间
	UpdateBy                            string             `gorm:"column:update_by" json:"update_by" form:"update_by" uri:"update_by" `                                                                                                                             // 修改人
}

func (FcProfitReportDay) TableName() string {
	return "fc_profit_report_day"
}
