General:
  # Debug | Release
  ENV: 'Debug'
  SHA256Salt: '123i1j2i3jiqewinajnjasdfnujaisdfhu1h23u1h2u3hnjqknjkansdjfnjxzcv'
  AesEcbKey: 'fhu1@12#1h2!3hnj'
  AesUserKey: 'bilIRkcuoNLmvZ0e'
  HttpProxy: ''
  DefaultCurrency: 'CNY'
  UploadFilePath: './upload'
  ApiSHA256Salt: 'xxfsdgdfh*328&**()(()'
  Ipdb: './config/city.ipdb'
  GoogleAuthFlag: false

Mysql:
  IsInit: true
  DSN: 'root:Lx_Bca0zj63322@(43.198.95.52:3306)/dev_game?charset=utf8&parseTime=true&loc=Local&tls=skip-verify'
  MaxOpenConn: 20
  MaxIdleConn: 20
  EncryptionDSN: false

MysqlSharding:
  IsInit: true
  DSN: 'root:Lx_Bca0zj63322@tcp(43.198.95.52:3306)/dev_game?charset=utf8mb4&parseTime=true'
  MaxOpenConn: 20
  MaxIdleConn: 20
  EncryptionDSN: false
  SkipInitializeWithVersion: false

Redis:
  IsInit: true
  Addr: '127.0.0.1:6379'
  Password: 'Zx_kj7112233'
  DB : 0
  PoolSize: 10



# Kafka
MQ:
  # false: 不启用,true:启用
  IsInit: false
  Kafka:
    #连接地址 ,分隔
    Addr: '43.198.225.80:9099'
    # 发送消息: false 同步方式, true异步方式
    IsAsync: false
    #版本号(关键)
    Version: '2.8.1'

Log:
  prefix: '[bootpkg]'
  log-file: true
  stdout: 'DEBUG'
  file: 'DEBUG'
  Log:
    prefix: 'go-api'
    log-file: true
    stdout: 'DEBUG'
    file: 'DEBUG'
    path: '/data/app/go-betconsumidor/go-betconsumidor.log'