-- Local menu name zh-cn update
START TRANSACTION;
UPDATE menu SET menu_name='活动管理', name='活动管理' WHERE role_flag='activity';
UPDATE menu SET menu_name='配置管理', name='配置管理' WHERE role_flag='cfgLst';
UPDATE menu SET menu_name='域名管理', name='域名管理' WHERE role_flag='domain';
UPDATE menu SET menu_name='财务管理', name='财务管理' WHERE role_flag='finance';
UPDATE menu SET menu_name='游戏管理', name='游戏管理' WHERE role_flag='gameManage';
UPDATE menu SET menu_name='首页管理', name='首页管理' WHERE role_flag='home';
UPDATE menu SET menu_name='日志管理', name='日志管理' WHERE role_flag='log';
UPDATE menu SET menu_name='渠道管理', name='渠道管理' WHERE role_flag='merchantChannel';
UPDATE menu SET menu_name='支付管理', name='支付管理' WHERE role_flag='payment';
UPDATE menu SET menu_name='权限管理', name='权限管理' WHERE role_flag='permission';
UPDATE menu SET menu_name='代理管理', name='代理管理' WHERE role_flag='proxy';
UPDATE menu SET menu_name='统计报表', name='统计报表' WHERE role_flag='statistics';
UPDATE menu SET menu_name='系统管理', name='系统管理' WHERE role_flag='systemManagement';
UPDATE menu SET menu_name='用户标签', name='用户标签' WHERE role_flag='userLabels';
UPDATE menu SET menu_name='用户管理', name='用户管理' WHERE role_flag='userManage';
UPDATE menu SET menu_name='优惠活动', name='优惠活动' WHERE role_flag LIKE '%/benefit/index';
UPDATE menu SET menu_name='每日签到', name='每日签到' WHERE role_flag LIKE '%/checkIn/index';
UPDATE menu SET menu_name='新活动', name='新活动' WHERE role_flag LIKE '%/newActivity/index';
UPDATE menu SET menu_name='公告管理', name='公告管理' WHERE role_flag LIKE '%/notice/index';
UPDATE menu SET menu_name='短信管理', name='短信管理' WHERE role_flag LIKE '%/shortMessageManagement/index';
UPDATE menu SET menu_name='任务管理', name='任务管理' WHERE role_flag LIKE '%/task/index';
UPDATE menu SET menu_name='卡券管理', name='卡券管理' WHERE role_flag LIKE '%/ticket/index';
UPDATE menu SET menu_name='广告配置', name='广告配置' WHERE role_flag LIKE '%/AdBannerConfiguration/index';
UPDATE menu SET menu_name='红利记录', name='红利记录' WHERE role_flag LIKE '%/BonusRecords/index';
UPDATE menu SET menu_name='VIP月礼记录', name='VIP月礼记录' WHERE role_flag LIKE '%/VIPMonthBonusRecords/index';
UPDATE menu SET menu_name='VIP周礼记录', name='VIP周礼记录' WHERE role_flag LIKE '%/VIPWeekBonusRecords/index';
UPDATE menu SET menu_name='版本管理', name='版本管理' WHERE role_flag LIKE '%/VersionManagement/index';
UPDATE menu SET menu_name='启动页配置', name='启动页配置' WHERE role_flag LIKE '%/appLoadingInterface/index';
UPDATE menu SET menu_name='艺术代理管理', name='艺术代理管理' WHERE role_flag LIKE '%/artProxyMgr/index';
UPDATE menu SET menu_name='导航配置', name='导航配置' WHERE role_flag LIKE '%/navConfig/index';
UPDATE menu SET menu_name='VIP升级记录', name='VIP升级记录' WHERE role_flag LIKE '%/vipUpgRec/index';
UPDATE menu SET menu_name='洗码配置', name='洗码配置' WHERE role_flag LIKE '%/washCode/index';
UPDATE menu SET menu_name='客服域名', name='客服域名' WHERE role_flag LIKE '%/customerServiceDomains/index';
UPDATE menu SET menu_name='资金流水', name='资金流水' WHERE role_flag LIKE '%/capitalFlow/index';
UPDATE menu SET menu_name='人工存提', name='人工存提' WHERE role_flag LIKE '%/manualDepositWithdrawal/index';
UPDATE menu SET menu_name='玩家充值', name='玩家充值' WHERE role_flag LIKE '%/playerTopUp/index';
UPDATE menu SET menu_name='玩家提现', name='玩家提现' WHERE role_flag LIKE '%/playerWithDrawal/index';
UPDATE menu SET menu_name='汇款申请', name='汇款申请' WHERE role_flag LIKE '%/remittanceApplication/index';
UPDATE menu SET menu_name='提现管理', name='提现管理' WHERE role_flag LIKE '%/withdrawal/index';
UPDATE menu SET menu_name='提现信息维护', name='提现信息维护' WHERE role_flag LIKE '%/withdrawalMessage/index';
UPDATE menu SET menu_name='游戏列表', name='游戏列表' WHERE role_flag LIKE '%/gameList/index';
UPDATE menu SET menu_name='游戏场馆', name='游戏场馆' WHERE role_flag LIKE '%/gameStadium/index';
UPDATE menu SET menu_name='商城列表', name='商城列表' WHERE role_flag LIKE '%/mallList/index';
UPDATE menu SET menu_name='商户管理', name='商户管理' WHERE role_flag LIKE '%/merchantManage/index';
UPDATE menu SET menu_name='跑马灯管理', name='跑马灯管理' WHERE role_flag LIKE '%/ticker/index';
UPDATE menu SET menu_name='IP黑名单', name='IP黑名单' WHERE role_flag LIKE '%/IPBlacklistManagement/index';
UPDATE menu SET menu_name='IP白名单', name='IP白名单' WHERE role_flag LIKE '%/IPWhitelistManagement/index';
UPDATE menu SET menu_name='账号信息', name='账号信息' WHERE role_flag LIKE '%/accountInfo/index';
UPDATE menu SET menu_name='账号安全', name='账号安全' WHERE role_flag LIKE '%/accountSafe/index';
UPDATE menu SET menu_name='产品统计', name='产品统计' WHERE role_flag LIKE '%/productStatistics/index';
UPDATE menu SET menu_name='告警监控', name='告警监控' WHERE role_flag LIKE '%/alarmMonitoring/index';
UPDATE menu SET menu_name='用户操作日志', name='用户操作日志' WHERE role_flag LIKE '%/userOperation/index';
UPDATE menu SET menu_name='商户玩家查询', name='商户玩家查询' WHERE role_flag LIKE '%/merchantPlayerQuery/index';
UPDATE menu SET menu_name='玩家查重', name='玩家查重' WHERE role_flag LIKE '%/playerDupeCheck/index';
UPDATE menu SET menu_name='银行卡管理', name='银行卡管理' WHERE role_flag LIKE '%/bankCard/index';
UPDATE menu SET menu_name='支付通道', name='支付通道' WHERE role_flag LIKE '%/channel/index';
UPDATE menu SET menu_name='渠道管理', name='渠道管理' WHERE role_flag LIKE '%/channelManagement/index';
UPDATE menu SET menu_name='商户列表', name='商户列表' WHERE role_flag LIKE '%/merchantList/index';
UPDATE menu SET menu_name='商户管理', name='商户管理' WHERE role_flag LIKE '%/merchantManagement/index';
UPDATE menu SET menu_name='商户提现', name='商户提现' WHERE role_flag LIKE '%/merchantWithdrawal/index';
UPDATE menu SET menu_name='支付通道管理', name='支付通道管理' WHERE role_flag LIKE '%/paymentChannelManagement/index';
UPDATE menu SET menu_name='支付网关管理', name='支付网关管理' WHERE role_flag LIKE '%/paymentGatewayManagement/index';
UPDATE menu SET menu_name='管理员管理', name='管理员管理' WHERE role_flag LIKE '%/admin/index';
UPDATE menu SET menu_name='渠道包管理', name='渠道包管理' WHERE role_flag LIKE '%/channelPackage/index';
UPDATE menu SET menu_name='菜单权限', name='菜单权限' WHERE role_flag LIKE '%/menu/index';
UPDATE menu SET menu_name='子渠道管理', name='子渠道管理' WHERE role_flag LIKE '%/subchannel/index';
UPDATE menu SET menu_name='代理域名管理', name='代理域名管理' WHERE role_flag LIKE '%/proxyDomMgmt/index';
UPDATE menu SET menu_name='代理列表', name='代理列表' WHERE role_flag LIKE '%/proxyList/index';
UPDATE menu SET menu_name='LTV分析', name='LTV分析' WHERE role_flag LIKE '%/LTV/index';
UPDATE menu SET menu_name='VIP用户分析', name='VIP用户分析' WHERE role_flag LIKE '%/VipUser/index';
UPDATE menu SET menu_name='安装追踪', name='安装追踪' WHERE role_flag LIKE '%/appInstallTracking/index';
UPDATE menu SET menu_name='落地页统计', name='落地页统计' WHERE role_flag LIKE '%/landingPage/index';
UPDATE menu SET menu_name='人工补单', name='人工补单' WHERE role_flag LIKE '%/manualReplenishment/index';
UPDATE menu SET menu_name='订单查询', name='订单查询' WHERE role_flag LIKE '%/orderQuery/index';
UPDATE menu SET menu_name='玩家账务报表', name='玩家账务报表' WHERE role_flag LIKE '%/playerAccountsReport/index';
UPDATE menu SET menu_name='玩家分组', name='玩家分组' WHERE role_flag LIKE '%/playerGrouping/index';
UPDATE menu SET menu_name='推广明细', name='推广明细' WHERE role_flag LIKE '%/promotionDetails/index';
UPDATE menu SET menu_name='推广ID报表', name='推广ID报表' WHERE role_flag LIKE '%/promotionIDReport/index';
UPDATE menu SET menu_name='推广报表', name='推广报表' WHERE role_flag LIKE '%/promotionReport/index';
UPDATE menu SET menu_name='对账报表', name='对账报表' WHERE role_flag LIKE '%/reconciliationReport/index';
UPDATE menu SET menu_name='留存分析', name='留存分析' WHERE role_flag LIKE '%/retention/index';
UPDATE menu SET menu_name='子游戏汇总', name='子游戏汇总' WHERE role_flag LIKE '%/subgameSummary/index';
UPDATE menu SET menu_name='汇总报表', name='汇总报表' WHERE role_flag LIKE '%/summaryReport/index';
UPDATE menu SET menu_name='热门游戏排行', name='热门游戏排行' WHERE role_flag LIKE '%/topGamesChart/index';
UPDATE menu SET menu_name='用户日报', name='用户日报' WHERE role_flag LIKE '%/userDailyReport/index';
UPDATE menu SET menu_name='部门管理', name='部门管理' WHERE role_flag LIKE '%/department/index';
UPDATE menu SET menu_name='字典类型', name='字典类型' WHERE role_flag LIKE '%/dictTypes/index';
UPDATE menu SET menu_name='字典数据', name='字典数据' WHERE role_flag LIKE '%/dicts/index';
UPDATE menu SET menu_name='菜单管理', name='菜单管理' WHERE role_flag LIKE '%/menus/index';
UPDATE menu SET menu_name='角色管理', name='角色管理' WHERE role_flag LIKE '%/role/index';
UPDATE menu SET menu_name='系统用户', name='系统用户' WHERE role_flag LIKE '%/systemUser/index';
UPDATE menu SET menu_name='标签管理', name='标签管理' WHERE role_flag LIKE '%/labels/index';
UPDATE menu SET menu_name='标签查询', name='标签查询' WHERE role_flag LIKE '%/labelsSeach/index';
UPDATE menu SET menu_name='手机验证码', name='手机验证码' WHERE role_flag LIKE '%/telCode/index';
UPDATE menu SET menu_name='转账管理', name='转账管理' WHERE role_flag LIKE '%/transferAccounts/index';
UPDATE menu SET menu_name='用户管理', name='用户管理' WHERE role_flag LIKE '%/user/index';
UPDATE menu SET menu_name='VIP管理', name='VIP管理' WHERE role_flag LIKE '%/vip/index';
UPDATE menu SET menu_name='VIP信息', name='VIP信息' WHERE role_flag LIKE '%/vipInfo/index';s